namespace: ""
env: "test"
hpa:
  minReplicas: 2
  maxReplicas: 3
  average_http_requests_hpa: 20
  average_cpu_hpa: 80

port: "3000"
targetPort: "3000"
replicaCount: 2
resources:
  requests:
    memory: "2500Mi"
    cpu: "2500m"
  limits:
    memory: "2500Mi"
    cpu: "2500m"

# wait for 120 * 10s to fail
startupProbe:
  failureThreshold: 120

# secret:
#   projectID: biconomy-test
#   key: bundlers
#   config:
#     name: config.json.enc

#   passphrase:
#     key: passphrase
#     name: CONFIG_PASSPHRASE
#     version: latest

# datadog configs
affinity_tolerations:
  enable: false

datadog:
  enable: true
  # gke_cluster_type: standard OR autopilot
  gke_cluster_type: autopilot
  # https://github.com/DataDog/dd-trace-js/releases
  dd_js_lib_version: v4.18.0
  env: "testing2"
  service: "sdk-relayer-service"
  version: "v3.15.0"
  configs:
    DD_TRACE_DEBUG: "true"
    DD_TRACE_STARTUP_LOGS: "false"
    DD_PROFILING_ENABLED: "true"
    DD_LOGS_INJECTION: "false"
    DD_RUNTIME_METRICS_ENABLED: "true"

  logs:
      enabled: false
      containerCollectAll: false
